config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match "/:project_id/warehouse", :controller => "products", :action => "index", :via => :get, :as => 'products'
match "/warehouse/new", :controller => "products", :action => "new", :via => :get, :as => 'new_product'
match "/warehouse/edit/:id", :controller => "products", :action => "edit", :via => :get, :as => 'product_edit'
match "/warehouse/create", :controller => "products", :action => "create", :via => :post, :as => 'create_product'
match "/warehouse/update/:id", :controller => "products", :action => "update", :via => :patch, :as => 'update_product'
match "/warehouse/show/:id", :controller => "products", :action => "show", :via => :get, :as => 'product_show'
match "/warehouse/destroy/:id", :controller => "products", :action => "destroy", :via => :delete, :as => 'destroy_product'

app/models/product.rb
class Product < ActiveRecord::Base
  include Redmine::SafeAttributes
  
  has_many :issues, :foreign_key => "issue_id"
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  safe_attributes 'name',
                  'price',
                  'amount',
                  'production_date',
                  'issue_id'
                  
  def safe_attributes=(attrs, user=User.current)
    attrs = delete_unsafe_attributes(attrs, user)
    return if attrs.empty?
    assign_attributes attrs, :without_protection => true
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_project
  before_action :find_product, :only => [:edit, :update, :show, :destroy]
  
  helper :queries
  helper :sort
  helper :products
  helper Redmine::MenuManager::MenuHelper
  include QueriesHelper
  include SortHelper
  include ProductsHelper

  def index
    retrieve_product_query
    
    if @query.valid?
      respond_to do |format|
        format.html {
          @product_count = @query.products(@project).count
          @product_pages = Paginator.new @product_count, per_page_option, params['page']
          @products = @query.products(@project, {:offset => @product_pages.offset, :limit => @product_pages.per_page})
          render :layout => !request.xhr?
        }
      end
      else
        respond_to do |format|
          format.html { render :layout => !request.xhr? }
        end
      end
      rescue ActiveRecord::RecordNotFound
      render_404
  end


  def new
    @product = Product.new
    @product.issue_id = params[:issue_id] if params[:issue_id]
  end


  def create
    unless User.current.allowed_to?(:add_products, @project, :global => true)
      raise ::Unauthorized
    end
    
    @product = Product.new
    @product.safe_attributes = (params[:product] || {}).deep_dup
    if @product.save
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_product_successful_create, :id => view_context.link_to("##{@product.id}", product_show_path(@product, :project_id => @project), :title => @product.name))
          redirect_to :action => 'index', :project_id => @project
        }
      end
      return
    else
      respond_to do |format|
        format.html {
          render :action => 'new'
          }
      end
    end
  end


  def edit
  end


  def update
    @product.safe_attributes = (params[:product] || {}).deep_dup
    if @product.save
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_product_successful_updated, :id => view_context.link_to("##{@product.id}", product_show_path(@product, :project_id => @project), :title => @product.name))
          redirect_to :action => 'index', :project_id => @project
        }
      end
      return
    else
      respond_to do |format|
        format.html {
          render :action => 'edit'
          }
      end
    end
  end
  
  def show
    respond_to do |format|
      format.html {
        render :template => 'products/show'
      }
      end
  end


  def destroy
    @product.destroy
    redirect_to :action => 'index', :project_id => @project
  end

  private

  def find_project
    @project = Project.find_by(:identifier => params["project_id"])
  end
  
  def find_product
    @product = Product.find(params[:id])
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  
  def product_column_content(column, item)
      value = column.value_object(item)
      value = Issue.find(value).to_s if column.name == :issue_id and value
      if value.is_a?(Array)
        values = value.collect {|v| column_value(column, item, v)}.compact
        safe_join(values, ', ')
      else
        products_column_value(column, item, value)
      end
  end
    
  def products_column_value(column, item, value)
      case column.name
        when :id
          link_to value, product_show_path(item, :project_id => @project)
        when :name
          link_to value, product_show_path(item, :project_id => @project)
      else
          format_object(value)
      end
  end
  
  def retrieve_product_query(klass=ProductQuery, use_session=true)
      session_key = klass.name.underscore.to_sym

      if params[:query_id].present?
        cond = "project_id IS NULL"
        cond << " OR project_id = #{@project.id}" if @project
        @query = klass.where(cond).find(params[:query_id])
        raise ::Unauthorized unless @query.visible?
        @query.project = @project
        session[session_key] = {:id => @query.id, :project_id => @query.project_id} if use_session
      elsif params[:set_filter] || session[session_key].nil?
        @query = klass.new(:name => "_", :project => @project)
        @query.build_from_params(params)
        session[session_key] = {:project_id => @query.project_id, :filters => @query.filters, :group_by => @query.group_by, :column_names => @query.column_names, :totalable_names => @query.totalable_names, :sort => @query.sort_criteria.to_a} if use_session
      else
        # retrieve from session
        @query = nil
        @query = klass.new(:name => "_", :filters => session[session_key][:filters], :group_by => session[session_key][:group_by], :column_names => session[session_key][:column_names], :totalable_names => session[session_key][:totalable_names], :sort_criteria => session[session_key][:sort])
        @query.project = @project
      end
      if params[:sort].present?
        @query.sort_criteria = params[:sort]
        if use_session
          session[session_key] ||= {}
          session[session_key][:sort] = @query.sort_criteria.to_a
        end
      end
      @query
    end

end

app/views/products/_actions.html.erb
<div class="contextual">
	<% if User.current.allowed_to?(:edit_products, @project, :global => true) %>
		<%= link_to l(:button_edit), product_edit_path(@product, :project_id => @project), :class => 'icon icon-edit' %>
	<% end %>
	<% if User.current.allowed_to?(:destroy_products, @project, :global => true) %>
		<%= link_to l(:button_delete), destroy_product_path(@product, :project_id => @project), :method => :delete, :class => 'icon icon-del' %>
	<% end %>
</div>

app/views/products/_form.html.erb
<%= labelled_fields_for :product, @product do |f| %>

	<%= hidden_field_tag 'back_url', params[:back_url], :id => nil if params[:back_url].present? %>

	<% if @product.safe_attribute? 'name' %>
		<p><%= f.text_field :name, :size => 50, :required => true %></p>
	<% end %>

	<% if @product.safe_attribute? 'price' %>
		<p><%= f.text_field :price, :size => 20 %></p>
	<% end %>

	<% if @product.safe_attribute? 'amount' %>
		<p><%= f.text_field :amount, :size => 20 %></p>
	<% end %>

	<% if @product.safe_attribute? 'production_date' %>
		<span id="production_date_area">
		<p><%= f.date_field(:production_date, :size => 10) %>
  		<%= calendar_for('product_production_date') %></p>
	<% end %>
		</span>
	<% if @product.safe_attribute? 'issue_id' %>
		<p id="related_issue"><%= f.text_field :issue_id, :size => 10 %></p>
		<%= javascript_tag "observeAutocompleteField('product_issue_id', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => Setting.cross_project_subtasks)}')" %>
	<% end %>

<% end %>

<% include_calendar_headers_tags %>

app/views/products/_list.html.erb
<% query_options = nil unless defined?(query_options) %>
<% query_options ||= {} %>

<div class="autoscroll">
<table class="list odd-even">
  <thead>
    <tr>
      <!-- ><th class="checkbox hide-when-print">
        <%#= check_box_tag 'check_all', '', false, :class => 'toggle-selection',:title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
      </th> -->
      <% @query.inline_columns.each do |column| %>
        <%= column_header(@query, column, query_options) %>
      <% end %>
    </tr>
  </thead>
  <tbody>
	  <% @products.each do |product| %>
	  <tr id="product-<%= product.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>" >
	      <!-- <td class="checkbox hide-when-print"><%#= check_box_tag("ids[]", product.id, false, :id => nil) %></td> -->
	      <% @query.inline_columns.each do |column| %>
	      	<%= content_tag('td', product_column_content(column, product), :class => column.css_classes) %>
	      <% end %>
	    </tr>
		<% end %>
  </tbody>
</table>
</div>

app/views/products/_sidebar.html.erb
<h3><%= l(:label_products) %></h3>

<%= render_sidebar_queries(ProductQuery, @project) %>

app/views/products/edit.html.erb
<h2><%= title l(:label_product_edit) %></h2>

<%= labelled_form_for @product, :url => {:controller => 'products', :action => 'update', :project_id => @project}, :html => {:id => 'issue-form', :multipart => true} do |f| %>

	<%= error_messages_for 'product' %>

	<div class="box tabular">
		<div id="all_attributes">
    		<%= render :partial => 'products/form', :locals => {:f => f} %>
		</div>
	</div>

	<%= submit_tag l(:button_submit) %>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'products/sidebar' %>
<% end %>

app/views/products/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:add_products, @project, :global => true) %>
    <%= link_to l(:label_product_new), new_product_path(@product, :project_id => @project), :class => 'icon icon-add' %>
  <% end %>
</div>

<h2><%= l(:products_list) %></h2>

<%= form_tag products_path(@project), :method => :get, :id => 'query_form' do %>
	<%= render :partial => 'queries/query_form' %>
<% end %>

<% if @products.empty? %>
	<div class="autoscroll">
		<p class="nodata"><%= l(:label_no_data) %></p>
	</div>
<% else %>
	<%= render_query_totals(@query) %>
	<%= render :partial => 'products/list', :locals => {:products => @products, :query => @query} %>
	<span class="pagination"><%= pagination_links_full @product_pages, @product_count %></span>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'products/sidebar' %>
<% end %>

<%#= context_menu %>

app/views/products/new.html.erb
<h2><%= title l(:label_product_new) %></h2>

<%= labelled_form_for @product, :url => {:controller => "products", :action => "create", :project_id => @project}, :html => {:id => 'product-form'} do |f| %>

	<%= error_messages_for 'product' %>

	<div class="box tabular">
		<div id="all_attributes">
    		<%= render :partial => 'products/form', :locals => {:f => f} %>
		</div>
	</div>

	<%= submit_tag l(:button_create) %>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'products/sidebar' %>
<% end %>

<% content_for :header_tags do %>
    <%= robot_exclusion_tag %>
<% end %>

app/views/products/show.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'style', :plugin => 'redmine_warehouse' %>
<% end %>

<%= render :partial => 'products/actions' %>

<h2> <%= @product.name %> </h2>

<div class="product">
	<div class="attributes">
		<% if @product.safe_attribute? 'name' %>
			<div class="attribute">
				<div class="label"> <%= l(:field_name) %>:</div>
				<div class="value"> <%= @product.name %> </div>
			</div>
		<% end %>
	
		<% if @product.safe_attribute? 'price' %>
			<div class="attribute">
				<div class="label"> <%= l(:field_price) %>: </div>
				<div class="value"> <%= @product.price.to_s %> </div>
			</div>
		<% end %>

		<% if @product.safe_attribute? 'amount' %>
			<div class="attribute">
				<div class="label"> <%= l(:field_amount) %>: </div>
				<div class="value"> <%= @product.amount.to_s %> </div>
			</div>
		<% end %>

		<% if @product.safe_attribute? 'production_date' %>
			<div class="attribute">
				<div class="label"> <%= l(:field_production_date) %>: </div>
				<div class="value"> <%= @product.production_date %> </div>
			</div>
		<% end %>
	
		<% if @product.safe_attribute? 'issue_id' %>
			<div class="attribute">
				<div class="label"> <%= l(:field_issue) %>: </div>
				<div class="value"> <%= Issue.find(@product.issue_id).to_s if @product.issue_id %> </div>
			</div>
		<% end %>
	</div>
</div>

<% content_for :sidebar do %>
    <%= render :partial => 'products/sidebar' %>
<% end %>